### ISSUE TITLE
No caching headers on tileserver resources

### ISSUE THREAD

**Issue by gjn** [geoadmin/tileserver-gl#5]
We should set appropriate caching headers, so that proxies and browsers can cache effecticely.

**Comment by danduk82** [comment]
@gjn , there is already @ltkum working on this (but there is no ticket afaik). I prefer to keep issues related to the configuration of vectortiles service in the corresponding repo. I close this one and I have opened [this other](https://github.com/geoadmin/config-tileservergl/issues/26)
